DROP SCHEMA IF EXISTS `mydb`;

-- MySQL Script generated by MySQL Workbench
-- seg 07 fev 2022 21:41:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DDDs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DDDs` (
  `id_DDDs` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_DDDs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Origin_destiny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Origin_destiny` (
  `id_origin_destiny` INT NOT NULL AUTO_INCREMENT,
  `origin` INT NOT NULL,
  `destiny` INT NOT NULL,
  `value` FLOAT NOT NULL,
  PRIMARY KEY (`id_origin_destiny`),
  INDEX `fk_origin_idx` (`origin` ASC) VISIBLE,
  INDEX `fk_destiny_idx` (`destiny` ASC) VISIBLE,
  CONSTRAINT `fk_origin`
    FOREIGN KEY (`origin`)
    REFERENCES `mydb`.`DDDs` (`id_DDDs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_destiny`
    FOREIGN KEY (`destiny`)
    REFERENCES `mydb`.`DDDs` (`id_DDDs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`DDDs`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`DDDs` (`id_DDDs`, `description`) VALUES (1, '011');
INSERT INTO `mydb`.`DDDs` (`id_DDDs`, `description`) VALUES (2, '016');
INSERT INTO `mydb`.`DDDs` (`id_DDDs`, `description`) VALUES (3, '017');
INSERT INTO `mydb`.`DDDs` (`id_DDDs`, `description`) VALUES (4, '018');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Origin_destiny`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
SET FOREIGN_KEY_CHECKS=0;
INSERT INTO `mydb`.`Origin_destiny` (`id_origin_destiny`, `origin`, `destiny`, `value`) VALUES (1, 011, 016, 1.90);
INSERT INTO `mydb`.`Origin_destiny` (`id_origin_destiny`, `origin`, `destiny`, `value`) VALUES (2, 016, 011, 2.90);
INSERT INTO `mydb`.`Origin_destiny` (`id_origin_destiny`, `origin`, `destiny`, `value`) VALUES (3, 011, 017, 1.70);
INSERT INTO `mydb`.`Origin_destiny` (`id_origin_destiny`, `origin`, `destiny`, `value`) VALUES (4, 017, 011, 2.70);
INSERT INTO `mydb`.`Origin_destiny` (`id_origin_destiny`, `origin`, `destiny`, `value`) VALUES (5, 011, 018, 0.90);
INSERT INTO `mydb`.`Origin_destiny` (`id_origin_destiny`, `origin`, `destiny`, `value`) VALUES (6, 018, 011, 1.90);

COMMIT;

